<?php

/** @var \Magento\Framework\Escaper $escaper */
$ajaxUrl = $block->getUrl('avanti-estimator/ajax/estimate');
?>
<div class="shipping-estimator" data-estimator='{"ajaxUrl":"<?= $escaper->escapeUrl($ajaxUrl) ?>"}'>
    <strong class="cep-title"><?= $escaper->escapeHtml(__('Calculate shipping')) ?></strong>

    <div class="shipping-wrapper">
        <div class="field">
            <input type="text" class="input-text cep" placeholder="Digite seu CEP" />
            <span class="nao-sabe-cep">Não sei meu CEP</span>
        </div>

        <button type="button" class="action primary estimate">
            <span><?= $escaper->escapeHtml(__('Estimate')) ?></span>
        </button>
    </div>

    <div class="results" style="margin-top:10px;"></div>
</div>

<script type="text/x-magento-init">
    {
  ".shipping-estimator": {
    "Avanti_ShippingEstimator/js/estimator": {}
  }
}
</script>