<?php
/** @var $block Magento\Framework\View\Element\Template */

?>

<div class="topbar-wrapper">
    <img src="<?php echo $block->getViewFileUrl('images/logo.svg'); ?>" alt="logo">

    <div class="progress-wrapper">
        <div class="carrinho">
            <span>1</span>
            <span>Carrinho</span>
        </div>
        <div class="entrega">
            <span>2</span>
            <span>Entrega</span>
        </div>
        <div class="pagamento">
            <span>3</span>
            <span>Pagamento</span>
        </div>
    </div>

    <div class="compra-segura">
        <img src="<?php echo $block->getViewFileUrl('images/shield.png'); ?>" alt="compra segura">
        <span>Compra 100% segura</span>
    </div>
</div>